apiVersion: v1
kind: Pod
metadata:
  name: downward
spec:
  containers:
    - name: main
      image: busybox
      command: ["sleep", "99999999"]
      resources:
        requests:
          cpu: "15m"
          memory: "100Ki"
        limits:
          cpu: "100m"
          memory: "4Mi"
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMEMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: CONTAINER_CPU_REQUEST_MILICORES
          valueFrom:
            resourceFieldRef:
              resource: requests.cpu
              divisor: 1m
        - name: CONTAINER_CPU_LIMIT_MILICORES
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
              divisor: 1m
        - name: CONTAINER_MEMORY_REQUEST_KIBIBYTES
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              divisor: 1Ki
        - name: CONTAINER_MEMORY_LIMIT_KIBIBYTES
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
              divisor: 1Ki
